### ISSUE TITLE
Webhook example

### ISSUE THREAD

**Issue by ohenepee** [drvirtuozov/botogram#1]

**Comment by drvirtuozov** [comment]
See readme. I've just updated it.

**Comment by ohenepee** [comment]
Still doesn't work since the express server doesn't have the `key` file nor the `cert` file... I tried setting up an HTTPS express server with all that and still doesn't work, I receive no updates from my bot

**Comment by drvirtuozov** [comment]
Try to generate the keys by following command:

`openssl req -newkey rsa:2048 -sha256 -nodes -keyout key.key -x509 -days 365 -out cert.pem -subj "/C=US/ST=New York/L=Brooklyn/O=Example Brooklyn Company/CN=YOURDOMAIN.EXAMPLE"`

Taken from [here](https://core.telegram.org/bots/self-signed). Replace **YOURDOMAIN.EXAMPLE** with yours IP or domain and then run the server as root with this configuration:

```javascript
const https = require("https");
const fs = require("fs");
const server = require("express")();
const bodyParser = require("body-parser");
const Botogram = require("botogram");
const bot = new Botogram("<TOKEN>");

server.use(bodyParser.json());

server.post("/", bot.listen);

bot.setWebhook({
  url: "https://${YOURIPORDOMAINHERE}:443",
  certificate: "cert.pem"
})
  .then(console.log)
  .catch(console.log);

bot.on("*", event => {
  bot.sendMessage({
    text: "Echo.",
    chat_id: event.from.id
  })
});

const sslOptions = {
  key: fs.readFileSync('key.key'),
  cert: fs.readFileSync('cert.pem'),
  passphrase: "test"
};

https.createServer(sslOptions, server).listen(443);
```

Also make sure that 443 port is open on your computer.

**Comment by ohenepee** [comment]
There's an issue with the `bot.listen` method.

The Express response object seems to have relocated the `body` element to `response.request.body`

That'll be a fix for `botogram.js line 49` or so ( _bodyHandler function )

I'm using the `bot.take` method to avoid it at the moment

Thanks for a great library and your help as well

**Comment by drvirtuozov** [comment]
Thanks for your response and participation. It's weird but it works fine for me. Which versions of express and body-parser do you use?

**Comment by ohenepee** [comment]
The latest of each... just did `npm install <module>' 3 days ago... well if it works for you then I was prolly doing something wrong...

Thanks again
