### ISSUE TITLE
Bot can't recieve messages from groups via Webhook

### ISSUE THREAD

**Issue by ohenepee** [drvirtuozov/botogram#2]
I even went as far as to **DISABLE** the privacy mode via `@BotFather` to allow the bot to recieve all group messages, but still "nothing".

Private chats work fine

**Comment by drvirtuozov** [comment]
I don't even know whose bug it is, because if to try to re-invite a bot with the new privacy mode to a group it's starting to work fine. Seems to be it's a Telegram-side bug.

**Comment by ohenepee** [comment]
Yeah... its a Telegram bug... I had to change my group's type from a public supergroup to a private supergroup to get my bot working... wierd but I've been jumping from library to library just bcos of this bug...
